title: YAZILIMLA UĞRAŞMAK...
description: Eğitici oyunlar, kelime tombalası, taksimetre hesaplama ve yazılım uygulamaları.
seo:
  name: Sonsuz Yaşam
  description: Eğitici oyunlar, kelime tombalası, taksimetre hesaplama, yaşlılar için dijital çözümler ve daha fazlası.
  type: WebSite
  url: https://sonsuzyasam.github.io
  twitter:
    username: arkeolojibiz
    card: summary_large_image
  facebook:
    publisher: https://www.facebook.com/arkeoloji.biz
    app_id: 335576833150842
  image: /assets/seo-banner.png
  locale: tr_TR
future: true
